### ISSUE TITLE
Optimize the packages 

### ISSUE THREAD

**Issue by kingsmen732** [kingsmen732/portfolio#1]
The packages have gone outdated and need to be optimized under new packages available for the same functionality.

**Comment by munnavuyyuru** [comment]
@kingsmen732 assign me

**Comment by kingsmen732** [comment]
I see you are interested in this issue @munnavuyyuru , I am assigning you with this issue

**Comment by babyo77** [comment]
i have added PR

**Comment by munnavuyyuru** [comment]
@kingsmen732 Two Lockfiles Detected! This can lead to inconsistent environment when updating packages .

**Comment by kingsmen732** [comment]
This issue is update with V1 patch
