### ISSUE TITLE
Resume Section not working

### ISSUE THREAD

**Issue by umar-9540** [kingsmen732/portfolio#17]
When I clicked on "Resume" in your portfolio, it is showing the home page instead of showing the resume. I can fix this issue.
Can you please assign this to me.

**Comment by kingsmen732** [comment]
yes i am assigning you with this issue

**Comment by umar-9540** [comment]
I have raised a PR. Please take a look

**Comment by kingsmen732** [comment]
fixed in https://github.com/kingsmen732/portfolio/pull/42
