### ISSUE TITLE
Adding a preview button in the projects modal

### ISSUE THREAD

**Issue by ash956901** [kingsmen732/portfolio#33]
From a recruiter's pov, the first thing he wants to see is a visual display of the projects you have done. Henceforth, we can add a preview button in the projects modal , which will open a slider preview for all the images of the project giving the recruiter a rich look and feel about your projects.

**Comment by kingsmen732** [comment]
Yes i admire this feature @ash956901 you are assigned to this feature

**Comment by ash956901** [comment]
will do asap sir, tnx for the reply ...

**Comment by ash956901** [comment]
Sir can you please close this issue as its already done by me?

**Comment by kingsmen732** [comment]
this issue is resolved in PR https://github.com/kingsmen732/portfolio/pull/31
