### ISSUE TITLE
More SVG to the collection 

### ISSUE THREAD

**Issue by kingsmen732** [kingsmen732/portfolio#4]
Add more svgs to choose from so user has more options to work on , lets say some might want to put out twitch , discord or other platforms along with experience

**Comment by 1-SubhamSingh** [comment]
Hey there ,
I am interested to work on this , can you assign me this.

**Comment by kingsmen732** [comment]
@1-SubhamSingh i am assigning you with this issue

**Comment by OmmDevgoswami** [comment]
Can i help in this contribution too @kingsmen732 ?

**Comment by babyo77** [comment]
i have added PR

**Comment by kingsmen732** [comment]
@OmmDevgoswami kindly look into [issue](https://github.com/kingsmen732/portfolio/pull/5) if you have any more to contribute to it kindly ping me with your intentions mentioned. I will assign this issue
