### ISSUE TITLE
Who am i ? tab

### ISSUE THREAD

**Issue by ParvamShah1** [kingsmen732/portfolio#54]
The text "who am i ?" is not visible in light mode .
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/4025b19d-b1bf-49ab-93ab-401d89e26301">
Please assign me this issue , i will work on it .

**Comment by mahirabidi12** [comment]
@kingsmen732 It still does not look good , give me an opportunity to make the required and much needed changes.

**Comment by ParvamShah1** [comment]
completed
