### ISSUE TITLE
adding a contact me form

### ISSUE THREAD

**Issue by sakshii00** [kingsmen732/portfolio#6]
I think a contact me form would be nice feature to add. You can let me know where you want to add it if you consider it

**Comment by kingsmen732** [comment]
Please do add the feature and we are open to stable features.

**Comment by kingsmen732** [comment]
okay @maxwithbug i am assigning you also on this feature so you can also help in this contribution

**Comment by aldol07** [comment]
I am working on it can you assign it to me.

**Comment by sakshii00** [comment]
@aldol07 The issue was assigned to me and I am currently working on it.
