### ISSUE TITLE
Make Experience SVG for different rankings 

### ISSUE THREAD

**Issue by kingsmen732** [kingsmen732/portfolio#8]
We currently have 3+ years of experience SVG ,  We would love to see similar themed for all levels of experience like

Levels of ranking proposed for now:
1. Rookie
2. Intermediate
3. Advanced
4. Fresher
5. 2,3,4,5+ years 
6. 6+years

### if you have better ranking system for people who can identify themselves with ease, please propose it

**Comment by zadescoxp** [comment]
hey @kingsmen732 assing me this I'll share you the figma designs with your needs

**Comment by zadescoxp** [comment]
![github2](https://github.com/user-attachments/assets/bd66b705-ec93-4e53-886d-bc9f40856d35)
![github1](https://github.com/user-attachments/assets/4133cb27-2267-450f-a42e-15ce3dcb2f48)
something like this may help

**Comment by kingsmen732** [comment]
Yes please , these designs look consistent. I am assigning you with this feature @zadescoxp

**Comment by zadescoxp** [comment]
hey @kingsmen732 added the pull req verify and merge it
