### ISSUE TITLE
Feat: Add a Open-source license to define usage rules

### ISSUE THREAD

**Issue by rajmanna-dev** [kingsmen732/portfolio#9]
### Improve Document
This is a open-source repo, so we need to add open-source license (like MIT License) on it to define rules for the outside usages.

Love to contribute on this repo, please assign me.

**Comment by kingsmen732** [comment]
Hey , i am assigning @rajmanna-dev in this issue

**Comment by rajmanna-dev** [comment]
Can you please add a hacktoberfest label on it?

To add a footer I have to create a separate footer Component so this is not a non-tech job.

**Comment by kingsmen732** [comment]
Kindly make a new issue for footer feature @rajmanna-dev
